# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YPCYK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YPCYK

  target 'YPCYKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YPCYKUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'YYKit', '~> 1.0.9'
pod 'Masonry', '~> 1.0.2'
end
